/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { Room } from './room';
import type { Transcript } from './transcript';

export interface Meeting {
  duration: number;
  id: number;
  name: string;
  room: Room;
  startTime: string;
  transcripts: Transcript[];
}
