/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */

export type MeetingStatus = (typeof MeetingStatus)[keyof typeof MeetingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MeetingStatus = {
  live: 'live',
  finished: 'finished',
} as const;
