/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { Users } from './users';
import type { Meeting } from './meeting';

export interface Transcript {
  createdBy: Users;
  end: string;
  id: number;
  meeting: Meeting;
  start: string;
  text: string;
}
