/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { UpdateMeetingDtoStatus } from './updateMeetingDtoStatus';

export interface UpdateMeetingDto {
  duration?: number;
  endTime?: string;
  name?: string;
  startTime?: string;
  status: UpdateMeetingDtoStatus;
}
