/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */

export type UpdateMeetingDtoStatus =
  (typeof UpdateMeetingDtoStatus)[keyof typeof UpdateMeetingDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMeetingDtoStatus = {
  live: 'live',
  finished: 'finished',
} as const;
