/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import type { Transcript } from './transcript';

export interface Users {
  id: number;
  password: string;
  transcripts: Transcript[];
  username: string;
}
