/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Hackathon DH API
 * WIP
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type { Meeting, Transcript, UpdateMeetingDto } from '.././model';
import { customInstance } from '.././mutator/custom-instance';
import type { ErrorType, BodyType } from '.././mutator/custom-instance';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * @summary Update a meeting by id
 */
export const meetingsControllerUpdate = (
  id: string,
  updateMeetingDto: BodyType<UpdateMeetingDto>,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    {
      url: `/meetings/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateMeetingDto,
    },
    options,
  );
};

export const getMeetingsControllerUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof meetingsControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateMeetingDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof meetingsControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateMeetingDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof meetingsControllerUpdate>>,
    { id: string; data: BodyType<UpdateMeetingDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return meetingsControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MeetingsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof meetingsControllerUpdate>>
>;
export type MeetingsControllerUpdateMutationBody = BodyType<UpdateMeetingDto>;
export type MeetingsControllerUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Update a meeting by id
 */
export const useMeetingsControllerUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof meetingsControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateMeetingDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof meetingsControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateMeetingDto> },
  TContext
> => {
  const mutationOptions = getMeetingsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Delete a meeting by id
 */
export const meetingsControllerRemove = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<void>(
    { url: `/meetings/${id}`, method: 'DELETE' },
    options,
  );
};

export const getMeetingsControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof meetingsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof meetingsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof meetingsControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return meetingsControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MeetingsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof meetingsControllerRemove>>
>;

export type MeetingsControllerRemoveMutationError = ErrorType<unknown>;

/**
 * @summary Delete a meeting by id
 */
export const useMeetingsControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof meetingsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof meetingsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getMeetingsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary Get one meeting by id with more details
 */
export const meetingsControllerGetOne = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Meeting>(
    { url: `/meetings/${id}`, method: 'GET', signal },
    options,
  );
};

export const getMeetingsControllerGetOneQueryKey = (id: string) => {
  return [`/meetings/${id}`] as const;
};

export const getMeetingsControllerGetOneQueryOptions = <
  TData = Awaited<ReturnType<typeof meetingsControllerGetOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof meetingsControllerGetOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getMeetingsControllerGetOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof meetingsControllerGetOne>>
  > = ({ signal }) => meetingsControllerGetOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof meetingsControllerGetOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type MeetingsControllerGetOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof meetingsControllerGetOne>>
>;
export type MeetingsControllerGetOneQueryError = ErrorType<unknown>;

/**
 * @summary Get one meeting by id with more details
 */
export const useMeetingsControllerGetOne = <
  TData = Awaited<ReturnType<typeof meetingsControllerGetOne>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof meetingsControllerGetOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getMeetingsControllerGetOneQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get all transcripts for a meeting
 */
export const meetingsControllerGetTranscripts = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<Transcript[]>(
    { url: `/meetings/${id}/transcripts`, method: 'GET', signal },
    options,
  );
};

export const getMeetingsControllerGetTranscriptsQueryKey = (id: string) => {
  return [`/meetings/${id}/transcripts`] as const;
};

export const getMeetingsControllerGetTranscriptsQueryOptions = <
  TData = Awaited<ReturnType<typeof meetingsControllerGetTranscripts>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof meetingsControllerGetTranscripts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getMeetingsControllerGetTranscriptsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof meetingsControllerGetTranscripts>>
  > = ({ signal }) =>
    meetingsControllerGetTranscripts(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof meetingsControllerGetTranscripts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type MeetingsControllerGetTranscriptsQueryResult = NonNullable<
  Awaited<ReturnType<typeof meetingsControllerGetTranscripts>>
>;
export type MeetingsControllerGetTranscriptsQueryError = ErrorType<unknown>;

/**
 * @summary Get all transcripts for a meeting
 */
export const useMeetingsControllerGetTranscripts = <
  TData = Awaited<ReturnType<typeof meetingsControllerGetTranscripts>>,
  TError = ErrorType<unknown>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof meetingsControllerGetTranscripts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getMeetingsControllerGetTranscriptsQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
